from typing import Annotated
from langgraph.graph import MessagesState
from typing import TypedDict


class DebateState(TypedDict):

    bulls_msg: Annotated[str, "Message from the Bulls side of the debate"]
    bears_msg: Annotated[str, "Message from the Bears side of the debate"]

    history: Annotated[str, "History of the debate so far"]

    last_msg: Annotated[str, "The last message sent in the debate"]
    judge_decision: Annotated[str, "Final decision made by the debate moderator"]

    rounds_completed: Annotated[int, "Number of debate rounds completed"]

class AgentState(MessagesState):
    ticker: Annotated[str, "ticker of the company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, lambda x, y: y]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Researcher of current world affairs"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # States
    debate_state: Annotated[DebateState, "State of the debate between Bulls and Bears"]

    # researcher team discussion step
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]